### 1.Import Numpy as Np

In [ ]:
import numpy as np

: 

### 2.Print Numpy version and Configuration

In [5]:
import numpy as np
print(np.__version__)
np.show_config()

2.5.0
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.5",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.33.112.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hob51hvs/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      

### 3. Create a null vector of size 10

In [6]:

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. Find memory size of any array

In [7]:

Z = np.zeros((10,10))
print(Z.size * Z.itemsize)

800


### 5. Get documentation of numpy.add

In [8]:

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### 6. Create a null vector of size 10 with the 5th value equal to 1

In [9]:

Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values from 10 to 49

In [10]:

Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector


In [11]:
Z = np.arange(10, 50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3×3 matrix with values from 0 to 8

In [12]:

Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements
)

In [14]:
Z = np.array([1,2,0,0,4,0])
print(np.nonzero(Z))

(array([0, 1, 4]),)


### 11. create a 3 by 3 identity matrix

In [15]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12.Create 3*3*3 array with random values

In [16]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.90806064 0.71328387 0.87568513]
  [0.02344584 0.84946426 0.9925723 ]
  [0.85456106 0.19640374 0.94176356]]

 [[0.79376034 0.36280975 0.40356677]
  [0.8229234  0.66214657 0.78250527]
  [0.66449679 0.34120541 0.36734903]]

 [[0.28323344 0.29237055 0.33200957]
  [0.98469833 0.65463746 0.39274306]
  [0.37107056 0.87712373 0.57613301]]]


### 13. Create a 10*10 random array and find min\max

In [18]:
Z =np.random.random((10,10))
print(Z.min(),Z.max())

0.012826151966131905 0.9906717287999726


### 14. Create a random vector of size 30 and find mean

In [19]:
Z= np.random.random(30)
print(Z.mean())

0.42418390539028505


### 15. Create a 2D array with 1 on the border and o inside

In [20]:
Z=np.ones((5,5))
Z[1:-1,1:-1]=0
print (Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 16. Add aborder (filled with 0) around an existing array

In [21]:
import numpy as np
Z= np.ones((5,5))
Z= np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following exprression?

In [ ]:
0*np.nan #nan
np.nan==np.nan #False
np.inf> np.absnp.nan-np.nan#nan
0.3==3*0.1 #False

### 18. Create a 5*5 matrix with values 1,2,3,4 just below the diagonal 

In [ ]:
Z= np.diag(1 + np.arrange(4),K=-1)
print(Z)

### 19. Create an 8*8 matrix and fill it with a checkboard pattern 

In [ ]:
Z= np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

### 20  . CONSIDER A SHAPE(6,7,8),WHAT IS THE INDEX OF THE 100TH ELEMENT

In [24]:
print (np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))
